name: lin

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run:  |
          sudo apt-get update
          sudo apt-get install libboost-dev openmpi-bin openmpi-common mpi-default-dev
      - name: test
        shell: bash
        run: |
          ./bootstrap-vcpkg.sh
          ./vcpkg install hermes
        continue-on-error: true
      - name: output
        run: cat  /home/runner/work/vcpkg/vcpkg/buildtrees/margo/config-x64-linux-dbg-err.log
