name: lin

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test
        shell: bash
        run: |
          ./bootstrap-vcpkg.sh
          ./vcpkg install hermes

