name: mac

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    name: mac
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          brew install automake boost libelf open-mpi
      - name: test
        run: |
          ./bootstrap-vcpkg.sh
          ./vcpkg install hermes