name: mac

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    name: mac
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          brew install automake boost gcc libelf libomp libtool llvm open-mpi
      - name: test
        run: |
          ls /opt/homebrew/opt/libomp/lib
          which g++
          export CXX1X="g++ -fopenmp"
          export CXX98="g++ -fopenmp"
          export CXX11="g++ -fopenmp"
          export CXX14="g++ -fopenmp"
          export CXX17"=g++ -fopenmp"
          export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/llvm/include -I/opt/homebrew/opt/libomp/include"
          export DYLD_LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:$DYLD_LIBRARY_PATH"
          export OpenMP_C_FLAGS="-Xclang -fopenmp"
          export OpenMP_C_LIB_NAMES="omp"
          export OpenMP_C_INCLUDE_DIR="/opt/homebrew/opt/libomp/include"
          export OpenMP_C_LIBRARY_DIR="/opt/homebrew/opt/libomp/lib"
          export OpenMP_CXX_FLAG="-Xclang -fopenmp"
          export OpenMP_CXX_INCLUDE_DIR="/opt/homebrew/opt/libomp/include"
          export OpenMP_CXX_LIB_NAMES="libomp"
          export VCPKG_C_FLAGS="-Xclang -fopenmp"
          export VCPKG_C_LIB_NAMES="omp"
          export VCPKG_C_INCLUDE_DIR="/opt/homebrew/opt/libomp/include"
          export VCPKG_C_LIBRARY_DIR="/opt/homebrew/opt/libomp/lib"
          export VCPKG_CXX_FLAG="-Xclang -fopenmp"
          export VCPKG_CXX_INCLUDE_DIR="/opt/homebrew/opt/libomp/include"
          export VCPKG_CXX_LIB_NAMES="libomp"	  
          ./bootstrap-vcpkg.sh
          env
          ./vcpkg install hermes
        continue-on-error: true
      - name: output
        run: cat  /Users/runner/work/vcpkg/vcpkg/buildtrees/hermes-shm/config-arm64-osx-out.log
