name: mac

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    name: mac
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          brew install automake boost libelf libomp libtool llvm open-mpi
      - name: test
        run: |
          ls /opt/homebrew/opt/libomp/lib
          export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
          export DYLD_LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:$DYLD_LIBRARY_PATH"
          export OpenMP_C_FLAGS="-fopenmp"
          export OpenMP_C_LIB_NAMES="omp"
          export OpenMP_C_INCLUDE_DIRS="/opt/homebrew/opt/libomp/include"
          export OpenMP_C_LIBRARY_DIRR="/opt/homebrew/opt/libomp/lib"
          ./bootstrap-vcpkg.sh
          ./vcpkg install hermes
        continue-on-error: true
      - name: output
        run: cat  /Users/runner/work/vcpkg/vcpkg/buildtrees/hermes-shm/config-arm64-osx-out.log
