name: mac

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    name: mac
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          brew install automake boost libelf libomp libtool open-mpi
      - name: test
        run: |
           export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
           export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
          ./bootstrap-vcpkg.sh
          ./vcpkg install hermes
        continue-on-error: true
      - name: output
        run: cat  /Users/runner/work/vcpkg/vcpkg/buildtrees/hermes-shm/config-arm64-osx-out.log
